# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

PACKAGE_NAME = "com.theblackbit.animemania.android"
BUNDLE_FILE_PATH = "app/release/app-release.aab"
KEYSTORE_PATH = "app/keystore.jks"
PLAY_STORE_KEY_PATH = "fastlane/secrets/pc-api-5201818442615982167-352-90e18ec40c6a.json"
GRADLE_FILE_PATH = "app/build.gradle.kts"
UPDATED_VERSION_CODE = 1
VERSION_NAME = "1.0.0-alpha"

default_platform(:android)

platform :android do
   desc 'Lint format'
   lane :lint_format do
   setup_ci if ENV['CI']
     gradle(task: "clean")
     gradle(task: "ktlintFormat")
   end

   desc 'Lint verification'
   lane :lint_verification do
   setup_ci if ENV['CI']
     gradle(task: "clean")
     gradle(task: "ktlintCheck")
   end

   desc 'Unit test verification'
   lane :unit_test_verification do
   setup_ci if ENV['CI']
     gradle(task: "clean")
     gradle(task: "testDebugUnitTest")
   end

   desc 'Generate coverage report'
   lane :coverage_report do
   setup_ci if ENV['CI']
     gradle(task: "clean")
     gradle(task: "jacocoMergedReport")
   end


   desc "get_play_store_version_code"
   private_lane :get_play_store_version_code do |options|
    version_code_from_play_store_strings = google_play_track_version_codes(
      track: options[:track],
      package_name: PACKAGE_NAME,
      json_key: PLAY_STORE_KEY_PATH)
      version_code_from_play_store = version_code_from_play_store_strings[0].to_i
      UPDATED_VERSION_CODE = version_code_from_play_store
   end

  desc "Responsible for fetching version code from play console and incrementing version code."
  private_lane :get_play_store_version_code_and_increment do
    get_play_store_version_code
    increment_version_code(
      gradle_file_path: GRADLE_FILE_PATH,
      version_code: UPDATED_VERSION_CODE.to_i + 1
      )
  end


  desc "Upload ABB to playStore"
  lane :deliver_abb do |options|
  setup_ci if ENV['CI']
    get_play_store_version_code_and_increment
    android_set_version_name(
      version_name: options[:version],
      gradle_file: GRADLE_FILE_PATH
     )
    gradle(task: "bundleRelease")
    upload_to_play_store(
       track: options[:track],
       aab: BUNDLE_FILE_PATH,
       json_key: PLAY_STORE_KEY_PATH,
       package_name: PACKAGE_NAME
      )
  end
end
