name: Deliver to beta

on:
  release:
    types: [published]
    tags:
      - 'v*.*.*-beta*'

jobs:
  beta:
    name: Deliver beta
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'    
      - run: |
          # Create a properties file using echo command
          echo "KITSU_API_URL=${{secrets.KITSU_API_URL}}" > ${{github.workspace}}/secrets.defaults.properties
          echo "ALIAS=${{secrets.ALIAS}}" >> ${{github.workspace}}/secrets.defaults.properties
          echo "KEY_PASS=${{secrets.KEY_PASS}}" >> ${{github.workspace}}/secrets.defaults.properties
          echo "KEY_ALIAS=${{secrets.KEY_ALIAS}}" >> ${{github.workspace}}/secrets.defaults.properties
      - uses: timheuer/base64-to-file@v1
        with:
          filename: '${{github.workspace}}/fastlane/secrets_play_console.json'
          encodedString: ${{ secrets.JSON_SECRET }}
      - run: |
          echo "${{secrets.JSON_SECRET}}" > ${{github.workspace}}/fastlane/secret_play_console.json.b64
          base64 -d -i ${{github.workspace}}/fastlane/secret_play_console.json.b64 > ${{github.workspace}}/fastlane/secret_play_console.json
      - run: fastlane supply init
      - run: mkdir -p ${{github.workspace}}/fastlane/metadata/android/en-US/changelogs
      - run: |
          # Create what's new section
          echo "${{env.CHANGE_LOG}}" > ${{github.workspace}}/fastlane/metadata/android/en-US/changelogs/${{ env.RELEASE_VERSION }}.txt
      - run: fastlane deliver_abb version:"${{ env.RELEASE_VERSION }}" track:"beta"
        
