name: Deliver to beta

on:
  release:
    types: created
    tags:
      - 'v*.*.*-beta'

jobs:
  beta:
    name: Deliver beta
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'    
      - run: |
          # Create a properties file using echo command
          echo "KITSU_API_URL=${{secrets.KITSU_API_URL}}" > ${{github.workspace}}/secrets.defaults.properties
          echo "ALIAS=${{secrets.ALIAS}}" >> ${{github.workspace}}/secrets.defaults.properties
          echo "KEY_PASS=${{secrets.KEY_PASS}}" >> ${{github.workspace}}/secrets.defaults.properties
          echo "KEY_ALIAS=${{secrets.KEY_ALIAS}}" >> ${{github.workspace}}/secrets.defaults.properties
     
      - run: |
          mkdir ${{github.workspace}}/fastlane/secrets 
      - run: cat ${{github.workspace}}/secrets.defaults.properties    
      - uses: jsdaniell/create-json@v1.2.2
        with:
          name: "pc-api-5201818442615982167-352-90e18ec40c6a.json"
          json: ${{secrets.PLAYSTORE_CREDENTIALS}}
          dir: '${{github.workspace}}/fastlane/secrets/'
      - run: |
          # Create JSON data using secrets and save to a file
          echo ${{ secrets.SECRET1 }} > ${{github.workspace}}/fastlane/secrets/pc-api-5201818442615982167-352-90e18ec40c6a.json
      - run: cat ${{github.workspace}}/fastlane/secrets/pc-api-5201818442615982167-352-90e18ec40c6a.json
      - uses: timheuer/base64-to-file@v1
        with:
          filename: '${{github.workspace}}/app/keystore.jks'
          encodedString: ${{ secrets.KEYSTORE }}
      - run: fastlane deliver_abb version:"${{ env.RELEASE_VERSION }}" track:"beta"
        
