name: Deliver to beta

on:
  release:
    types: created
    tags:
      - 'v*-beta*'

jobs:
  beta:
    name: Deliver beta
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'    
      - uses: christian-draeger/write-properties@1.1.0
        with:
          path: '${{github.workspace}}secrets.defaults.properties'
          property: |
            'KITSU_API_URL'
            'ALIAS'
            'KEY_PASS'
            'KEY_ALIAS'
          value: |
            "${{secrets.KITSU_API_URL}}"
            ${{secrets.ALIAS}}
            ${{secrets.KEY_PASS}}
            ${{secrets.KEY_ALIAS}}
      - uses: christian-draeger/write-properties@1.1.0 
        with:
          name: "pc-api-5201818442615982167-352-90e18ec40c6a.json"
          json: ${{secrets.PLAYSTORE_CREDENTIALS}}
          dir: '${{github.workspace}}/fastlane/secrets/'
      - uses: timheuer/base64-to-file@v1
        with:
          filename: '${{github.workspace}}/app/keystore.jks'
          encodedString: ${{ secrets.KEYSTORE }}
      - run: fastlane deliver_abb version:"${{ env.RELEASE_VERSION }}" track:"beta"
        
