name: Deliver to beta

on:
  release:
    types: created
    tags:
      - 'v*.*.*-beta'

jobs:
  beta:
    name: Deliver beta
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'    
      - run: |
          # Create a properties file using echo command
          echo "KITSU_API_URL=${{secrets.KITSU_API_URL}}" > ${{github.workspace}}/secrets.defaults.properties
          echo "ALIAS=${{secrets.ALIAS}}" >> ${{github.workspace}}/secrets.defaults.properties
          echo "KEY_PASS=${{secrets.KEY_PASS}}" >> ${{github.workspace}}/secrets.defaults.properties
          echo "KEY_ALIAS=${{secrets.KEY_ALIAS}}" >> ${{github.workspace}}/secrets.defaults.properties
      - uses: timheuer/base64-to-file@v1
        with:
          filename: '${{github.workspace}}/fastlane/secrets_play_console.json'
          encodedString: ${{ secrets.JSON_SECRET }}
      - uses: timheuer/base64-to-file@v1
        with:
          filename: '${{github.workspace}}/app/keystore.jks'
          encodedString: ${{ secrets.KEYSTORE }}
      - run: fastlane deliver_abb version:"${{ env.RELEASE_VERSION }}" track:"beta"
        
