name: Ktlint format and verify
run-name: ${{ github.actor }} Running linter
on:
  pull_request:
    types: [opened, reopened, edited]
    branches:
      - 'master'
      - 'develop'

jobs:
  Run-Linter:
    name: Run ktlint
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - run: |
          # Create a properties file using echo command
          echo 'KITSU_API_URL="${{secrets.KITSU_API_URL}}"' > ${{github.workspace}}/secrets.defaults.properties
          echo "ALIAS=${{secrets.ALIAS}}" >> ${{github.workspace}}/secrets.defaults.properties
          echo "KEY_PASS=${{secrets.KEY_PASS}}" >> ${{github.workspace}}/secrets.defaults.properties
          echo "KEY_ALIAS=${{secrets.KEY_ALIAS}}" >> ${{github.workspace}}/secrets.defaults.properties
      - run: fastlane lint_format
      - run: fastlane lint_verification
