name: Ktlint format and verify
run-name: ${{ github.actor }} Running linter
on:
  pull_request:
    types: [opened, reopened]
    branches:
      - 'master'
      - 'develop'

jobs:
  Run-Linter:
    name: Run ktlint
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - run: fastlane lint_format
      - run: fastlane lint_verification
